Interface  {
  Inputs {
    Field input0 { type = image }
  }
  Outputs {
    Field lungs_unfilled { internalName = PythonImage.output0 }
    Field lungs_trachea_mask {internalName = PythonImage1.output0 }
    Field difference {internalName = PythonImage2.output0}
    Field trachea {internalName = PythonImage3.output0}
  }
  
  
  Parameters {
    Field overallMeanValue { type = double editable = no }
  }
}

Commands {
  source = $(LOCAL)/LungSegmentation.py
}
